# Generated by Django 3.0 on 2020-03-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecog', '0003_logincredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'CollegeDetails',
            },
        ),
    ]
