# Generated by Django 3.0 on 2020-03-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerecog', '0004_collegedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
    ]
